"""Create user model

Revision ID: 188f1469ea75
Revises: 5e9c548d7184
Create Date: 2022-12-16 18:05:18.137262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188f1469ea75'
down_revision = '5e9c548d7184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
