"""Create user model

Revision ID: 5e9c548d7184
Revises: 758cf6ea406f
Create Date: 2022-11-27 21:59:53.732634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9c548d7184'
down_revision = '758cf6ea406f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
